name:                edit-distance-linear-bench
version:             0.1.0.0
github:              "0xd34df00d/edit-distance-linear-bench"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/edit-distance-linear-bench#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- inline-c-cpp
- vector

ghc-options:
- -Wall

extra-libraries:
- stdc++

library:
  source-dirs: src

executables:
  edit-distance-linear-bench-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - edit-distance-linear-bench

benchmarks:
  edit-distance-linear-benchmarks:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -rtsopts
    dependencies:
    - edit-distance-linear-bench
    - criterion
    - text
    - text-metrics

tests:
  edit-distance-linear-bench-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - edit-distance
    - edit-distance-linear-bench
    - hspec
    - QuickCheck
